name: ðŸš€ Sync All Branches

on:
  schedule:
    - cron: "0 0 * * *"  # æ¯å¤© UTC æ—¶é—´ 0:00 è§¦å‘ä¸€æ¬¡
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          repository: CyrusZhou-CN/ET
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1
          
      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
      - name: Add and fetch from remote repository
        run: |
          REMOTE_REPO="egametang/ET"
          
          # æ·»åŠ è¿œç¨‹ä»“åº“
          REMOTE_URL="https://github.com/$REMOTE_REPO.git"
          git remote add upstream $REMOTE_URL
          
          # èŽ·å–è¿œç¨‹åˆ†æ”¯å’Œæ ‡ç­¾
          git fetch upstream --tags
          git push --tags --progress "origin"
      - name: Sync all branches
        run: |
          REMOTE_REPO="egametang/ET"
          LOCAL_REPO="CyrusZhou-CN/ET"
          
          # èŽ·å–æ‰€æœ‰è¿œç¨‹åˆ†æ”¯
          REMOTE_BRANCHES=$(gh api repos/$REMOTE_REPO/branches  --paginate  --jq '.[].name')
          LOCAL_BRANCHES=$(gh api repos/$LOCAL_REPO/branches  --paginate  --jq '.[].name')
          
          for branch in $REMOTE_BRANCHES; do
            echo "Checking if local branch $branch exists"
            if echo "$LOCAL_BRANCHES" | grep -E "^$branch$" > /dev/null; then
              echo "Syncing branch: $branch"
              gh repo sync $LOCAL_REPO -b $branch --force
            else
              echo "Local branch $branch exists, syncing..."
              # åˆ›å»ºæœ¬åœ°åˆ†æ”¯å¹¶è®¾ç½®ä¸ºè·Ÿè¸ªè¿œç¨‹åˆ†æ”¯
              git checkout -b $branch upstream/$branch
              git push origin $branch
            fi
          done

      - name: Push tags to own repo
        run: |
          git remote update --prune
      - name: Cleanup
        run: |
          git gc --prune=now
